version: '2'
services:
    entmdm-app:
        image: entmdm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://entmdm-mysql:3306/entmdm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=entmdm-elasticsearch:9300
        ports:
            - 8080:8080
    entmdm-mysql:
        extends:
            file: mysql.yml
            service: entmdm-mysql
    entmdm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: entmdm-elasticsearch
